import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Movie from './models/Movie.js';

dotenv.config();

/**
 * GIẢI PHÁP ẢNH MỞ (OPEN-SOURCE IMAGE PROXY):
 * Sử dụng wsrv.nl - một dịch vụ proxy ảnh mã nguồn mở cực kỳ mạnh mẽ và an toàn.
 * Nó giúp:
 * 1. Vượt qua mọi rào cản Hotlinking/Referer của các server ảnh (TMDB, IMDb...).
 * 2. Tự động tối ưu hóa ảnh sang định dạng WebP (nhẹ hơn, load nhanh hơn).
 * 3. Đảm bảo hiển thị 100% trên mọi môi trường (localhost, production).
 */
const getOpenSourceImageUrl = (url) => {
    if (!url) return 'https://placehold.co/500x750?text=No+Poster';
    // wsrv.nl sẽ xử lý ảnh, đảm bảo an toàn và hiển thị 100%
    return `https://wsrv.nl/?url=${encodeURIComponent(url)}&w=500&h=750&fit=cover&output=webp&noretina=1`;
};

const finalMoviesData = [
    // --- 30 PHIM GỐC ---
    { title: "Upgraded", rating: 6.1, totalrating: 31000, description: "Ana, an ambitious intern at an art auction house in New York City, misrepresents herself to a handsome wealthy man as the director.", image: "https://image.tmdb.org/t/p/w500/eYsdP5QffklSZMXJMy295xTHKmt.jpg", releaseDate: "2024-02-09", duration: 105, genres: "Romance, Comedy, Drama", videoUrl: "https://www.youtube.com/watch?v=P3_dj7BnHp8" },
    { title: "Anyone But You", rating: 6.9, totalrating: 140000, description: "After an amazing first date, Bea and Ben's fiery attraction turns ice cold — until they find themselves unexpectedly reunited.", image: "https://image.tmdb.org/t/p/w500/5aKu986S69vWo7vY99A997BInpM.jpg", releaseDate: "2023-12-22", duration: 103, genres: "Romance, Comedy", videoUrl: "https://www.youtube.com/watch?v=UtjH6Sk7Gxs" },
    { title: "The Idea of You", rating: 7.5, totalrating: 93000, description: "Solène, a 40-year-old single mom, begins an unexpected romance with 24-year-old Hayes Campbell.", image: "https://image.tmdb.org/t/p/w500/x9779S9Px7v2Sux8TMvIB90jtht.jpg", releaseDate: "2024-05-02", duration: 115, genres: "Romance, Comedy, Drama", videoUrl: "https://www.youtube.com/watch?v=V8i6PB0gGOA" },
    { title: "Ticket to Paradise", rating: 6.7, totalrating: 29000, description: "A divorced couple teams up and travels to Bali to stop their daughter from making the same mistake.", image: "https://image.tmdb.org/t/p/w500/r97Y7UuZbeuhvDtB69yhr69CUXh.jpg", releaseDate: "2022-09-08", duration: 104, genres: "Romance, Comedy", videoUrl: "https://www.youtube.com/watch?v=hkP4tVTdsz8" },
    { title: "No Hard Feelings", rating: 7.1, totalrating: 247000, description: "On the brink of losing her home, a woman is hired by a wealthy couple to date their introverted 19-year-old son.", image: "https://image.tmdb.org/t/p/w500/6vS7I76XZST7Oasq7tL6pA8398r.jpg", releaseDate: "2023-06-21", duration: 103, genres: "Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=kIcLb0KAJAs" },
    { title: "Asteroid City", rating: 6.6, totalrating: 150000, description: "The itinerary of a Junior Stargazer/Space Cadet convention is spectacularly disrupted by world-changing events.", image: "https://image.tmdb.org/t/p/w500/6n76mNnZ6pW9U6TzXj5x6m8L6W0.jpg", releaseDate: "2023-06-09", duration: 105, genres: "Comedy, Drama", videoUrl: "https://www.youtube.com/watch?v=9FXCSXuGTF4" },
    { title: "Past Lives", rating: 7.9, totalrating: 1200000, description: "Nora and Hae Sung, two deeply connected childhood friends, are wrested apart after Nora's family emigrates.", image: "https://image.tmdb.org/t/p/w500/pA3Y2mZ7aGjS69vWo7vY99A997B.jpg", releaseDate: "2023-06-02", duration: 106, genres: "Drama, Romance", videoUrl: "https://www.youtube.com/watch?v=kA244xewjcI" },
    { title: "Rye Lane", rating: 7.3, totalrating: 41000, description: "Two youngsters reeling from bad break-ups connect over the course of an eventful day in South London.", image: "https://image.tmdb.org/t/p/w500/mIBG7InLoguS4997v8mGZ6J9zUv.jpg", releaseDate: "2023-03-17", duration: 82, genres: "Romance, Comedy", videoUrl: "https://www.youtube.com/watch?v=SqcF_GI3mOA" },
    { title: "Theater Camp", rating: 7.0, totalrating: 43000, description: "The eccentric staff must band together with her clueless son to keep the camp afloat.", image: "https://image.tmdb.org/t/p/w500/9Gl696X97S679SfcY9X73K7v2.jpg", releaseDate: "2023-07-14", duration: 94, genres: "Comedy", videoUrl: "https://www.youtube.com/watch?v=puVDIUk0kM8" },
    { title: "A Good Person", rating: 7.6, totalrating: 90000, description: "Allison forms an unlikely relationship with her would-be father-in-law that helps her navigate grief.", image: "https://image.tmdb.org/t/p/w500/74xTEgt7R36FpZ6p69786vS8n63.jpg", releaseDate: "2023-03-24", duration: 129, genres: "Drama", videoUrl: "https://www.youtube.com/watch?v=phRXBLwcy5I" },
    { title: "What Happens Later", rating: 5.8, totalrating: 12000, description: "Two ex-lovers, Bill and Willa, get snowed in at a regional airport overnight.", image: "https://image.tmdb.org/t/p/w500/8Gxv3mYgiFAHUqvXo89vMvUNpY4.jpg", releaseDate: "2023-11-03", duration: 104, genres: "Romance, Comedy", videoUrl: "https://www.youtube.com/watch?v=zceSigCGWSQ" },
    { title: "Maybe I Do", rating: 5.9, totalrating: 10000, description: "Michelle and Allen decide it's time to introduce their parents to each other.", image: "https://image.tmdb.org/t/p/w500/iuFNmBTD0Atv4vT0C9QwoS6p3QT.jpg", releaseDate: "2023-01-27", duration: 95, genres: "Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=Z11QkNvMZpc" },
    { title: "Love Again", rating: 6.8, totalrating: 59000, description: "A young woman tries to ease the pain of her fiancé's death by sending romantic texts.", image: "https://image.tmdb.org/t/p/w500/d5N0unRiSFEfp6pSGsYArasNc4S.jpg", releaseDate: "2023-05-05", duration: 104, genres: "Comedy, Drama, Romance", videoUrl: "https://www.youtube.com/watch?v=CQDXtD2HJAs" },
    { title: "Red, White & Royal Blue", rating: 7.9, totalrating: 190000, description: "The feud between the US President's son and a British prince threatens relations.", image: "https://image.tmdb.org/t/p/w500/62HCnUTziyMC96wYvUaPZpViZld.jpg", releaseDate: "2023-08-10", duration: 121, genres: "Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=pt56IC8gDZ4" },
    { title: "You Hurt My Feelings", rating: 6.3, totalrating: 9000, description: "A novelist's marriage is upended when she overhears her husband's honest reaction to her book.", image: "https://image.tmdb.org/t/p/w500/r9p9p7v5Mhp9HpjR9p9p7v5Mhp9.jpg", releaseDate: "2023-05-26", duration: 93, genres: "Comedy, Drama, Romance", videoUrl: "https://www.youtube.com/watch?v=20GWk5cWPBs" },
    { title: "Challengers", rating: 7.4, totalrating: 145000, description: "Tashi signs her husband up for a 'Challenger' event where he faces her ex-boyfriend.", image: "https://image.tmdb.org/t/p/w500/9986S69vWo7vY99A997BInpM5aKu.jpg", releaseDate: "2024-04-18", duration: 131, genres: "Drama, Romance", videoUrl: "https://www.youtube.com/watch?v=MDnVk5jIJr0" },
    { title: "The Color Purple", rating: 7.3, totalrating: 21000, description: "A story spanning forty years in the life of Celie, an African-American woman in the South.", image: "https://image.tmdb.org/t/p/w500/vV9Sux8TMvIB90jthtx9779S9Px7.jpg", releaseDate: "1985-12-18", duration: 154, genres: "Drama", videoUrl: "https://www.youtube.com/watch?v=wPwzBUui1GA" },
    { title: "Poor Things", rating: 8.0, totalrating: 1100000, description: "Brought back to life by an unorthodox scientist, a young woman runs off on an adventure.", image: "https://image.tmdb.org/t/p/w500/kxySux8TMvIB90jthtx9779S9Px7v2.jpg", releaseDate: "2023-12-08", duration: 142, genres: "Sci-Fi, Romance, Comedy, Drama", videoUrl: "https://www.youtube.com/watch?v=ZFu7ZH4y6J4" },
    { title: "Are You There God? It's Me, Margaret.", rating: 7.5, totalrating: 45000, description: "An 11-year-old girl navigates new friends, feelings, and the beginning of adolescence.", image: "https://image.tmdb.org/t/p/w500/vV9Sux8TMvIB90jthtx9779S9Px7.jpg", releaseDate: "2023-04-23", duration: 106, genres: "Comedy, Drama, Family", videoUrl: "https://www.youtube.com/watch?v=LzRzojHC3iE" },
    { title: "Bottoms", rating: 7.0, totalrating: 38000, description: "Unpopular best friends PJ and Josie start a high school fight club to meet girls.", image: "https://image.tmdb.org/t/p/w500/vV9Sux8TMvIB90jthtx9779S9Px7.jpg", releaseDate: "2023-08-25", duration: 91, genres: "Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=xb7v8ZXPkSM" },
    { title: "The Lost City", rating: 6.7, totalrating: 345000, description: "A reclusive romance novelist gets swept up in a kidnapping attempt in the jungle.", image: "https://image.tmdb.org/t/p/w500/ne9jthtx9779S9Px7v2Sux8TMvIB.jpg", releaseDate: "2022-03-25", duration: 112, genres: "Action, Adventure, Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=nfKO9rYDmE8" },
    { title: "Marry Me", rating: 6.5, totalrating: 150000, description: "Kat Valdez decides to marry a stranger in the crowd after learning her partner cheated.", image: "https://image.tmdb.org/t/p/w500/ne9jthtx9779S9Px7v2Sux8TMvIB.jpg", releaseDate: "2022-02-09", duration: 112, genres: "Comedy, Romance, Music", videoUrl: "https://www.youtube.com/watch?v=Ebv9_rNb5Ig" },
    { title: "Bros", rating: 6.4, totalrating: 54000, description: "Two gay men in Manhattan who avoid commitment are drawn to each other.", image: "https://image.tmdb.org/t/p/w500/ne9jthtx9779S9Px7v2Sux8TMvIB.jpg", releaseDate: "2022-09-30", duration: 115, genres: "Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=BQIeBB9XMe8" },
    { title: "Shotgun Wedding", rating: 6.3, totalrating: 93000, description: "Darcy and Tom's destination wedding is taken hostage.", image: "https://image.tmdb.org/t/p/w500/ne9jthtx9779S9Px7v2Sux8TMvIB.jpg", releaseDate: "2022-12-28", duration: 100, genres: "Action, Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=qNVwRHQL8jw" },
    { title: "Your Place or Mine", rating: 6.0, totalrating: 72000, description: "Best friends Debbie and Peter swap homes for a week.", image: "https://image.tmdb.org/t/p/w500/ne9jthtx9779S9Px7v2Sux8TMvIB.jpg", releaseDate: "2023-02-10", duration: 109, genres: "Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=5JyfgkPMXk0" },
    { title: "Ghosted", rating: 6.7, totalrating: 120000, description: "Cole falls head over heels for Sadie — but then makes the discovery that she’s a secret agent.", image: "https://image.tmdb.org/t/p/w500/ne9jthtx9779S9Px7v2Sux8TMvIB.jpg", releaseDate: "2023-04-21", duration: 116, genres: "Action, Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=IAdCsNtEuBU" },
    { title: "A Family Affair", rating: 5.7, totalrating: 33000, description: "A surprising romance kicks off comic consequences for a young woman.", image: "https://image.tmdb.org/t/p/w500/ne9jthtx9779S9Px7v2Sux8TMvIB.jpg", releaseDate: "2024-06-28", duration: 111, genres: "Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=Ytc2eifpiuQ" },
    { title: "Mother of the Bride", rating: 5.4, totalrating: 29000, description: "A doting mom discovers the groom's father is her ex.", image: "https://image.tmdb.org/t/p/w500/ne9jthtx9779S9Px7v2Sux8TMvIB.jpg", releaseDate: "2024-05-09", duration: 89, genres: "Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=bUSoEQBHtSg" },
    { title: "Players", rating: 6.3, totalrating: 41000, description: "New York sportswriter Mack unexpectedly falls for one of her targets.", image: "https://image.tmdb.org/t/p/w500/ne9jthtx9779S9Px7v2Sux8TMvIB.jpg", releaseDate: "2024-02-14", duration: 105, genres: "Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=8gH6AEBwEAw" },
    { title: "About My Father", rating: 6.4, totalrating: 21000, description: "Sebastian's Italian immigrant father Salvo insists on crashing a weekend with her parents.", image: "https://image.tmdb.org/t/p/w500/ne9jthtx9779S9Px7v2Sux8TMvIB.jpg", releaseDate: "2023-05-26", duration: 89, genres: "Comedy", videoUrl: "https://www.youtube.com/watch?v=txLSE7tpgr0" },

    // --- 50 PHIM BOM TẤN MỚI ---
    { title: "Avatar: The Way of Water", rating: 7.6, totalrating: 450000, description: "Jake Sully lives with his newfound family on Pandora.", image: "https://image.tmdb.org/t/p/w500/t6Sna4v9S6JS4vgUnSBD9zSHe34.jpg", releaseDate: "2022-12-16", duration: 192, genres: "Action, Adventure, Sci-Fi", videoUrl: "https://www.youtube.com/watch?v=d9MyW72ELq0" },
    { title: "The Super Mario Bros. Movie", rating: 7.1, totalrating: 280000, description: "The story of The Super Mario Bros. on their journey through the Mushroom Kingdom.", image: "https://image.tmdb.org/t/p/w500/qNBAXBIQlnOThr6VMB6mU21wS1Z.jpg", releaseDate: "2023-04-05", duration: 92, genres: "Animation, Adventure, Comedy", videoUrl: "https://www.youtube.com/watch?v=TnGl01FkMMo" },
    { title: "Spider-Man: Across the Spider-Verse", rating: 8.7, totalrating: 320000, description: "Miles Morales catapults across the Multiverse.", image: "https://image.tmdb.org/t/p/w500/8VtB9m91SpxI6Gjo9mZUR6BPMY5.jpg", releaseDate: "2023-06-02", duration: 140, genres: "Animation, Action, Adventure", videoUrl: "https://www.youtube.com/watch?v=shW9i6k8cB0" },
    { title: "John Wick: Chapter 4", rating: 7.7, totalrating: 250000, description: "John Wick uncovers a path to defeating The High Table.", image: "https://image.tmdb.org/t/p/w500/vZloFAK7NmvMGKE7Vk6set85QN4.jpg", releaseDate: "2023-03-24", duration: 169, genres: "Action, Crime, Thriller", videoUrl: "https://www.youtube.com/watch?v=qEVUtrk8_B4" },
    { title: "Guardians of the Galaxy Vol. 3", rating: 7.9, totalrating: 290000, description: "Peter Quill rallies his team to defend the universe.", image: "https://image.tmdb.org/t/p/w500/r2J0vUsesmS3M6fiuBnmB176zST.jpg", releaseDate: "2023-05-05", duration: 150, genres: "Action, Adventure, Comedy", videoUrl: "https://www.youtube.com/watch?v=u3V5KDHRQvk" },
    { title: "The Flash", rating: 6.7, totalrating: 180000, description: "Barry Allen uses his super speed to change the past.", image: "https://image.tmdb.org/t/p/w500/rktDFPzHwy79bbU9nkqs2ki3jdy.jpg", releaseDate: "2023-06-16", duration: 144, genres: "Action, Adventure, Sci-Fi", videoUrl: "https://www.youtube.com/watch?v=hebWYacbdvc" },
    { title: "Elemental", rating: 7.0, totalrating: 150000, description: "Fire-, water-, land- and air-residents live together in Element City.", image: "https://image.tmdb.org/t/p/w500/4Y9HpkEE69vSTB0o6CU9t9p9vU6.jpg", releaseDate: "2023-06-16", duration: 101, genres: "Animation, Adventure, Comedy", videoUrl: "https://www.youtube.com/watch?v=hXzcyx9V0xw" },
    { title: "Mission: Impossible - Dead Reckoning", rating: 7.8, totalrating: 140000, description: "Ethan Hunt and his IMF team track down a dangerous weapon.", image: "https://image.tmdb.org/t/p/w500/NNxpe91uWp6GZ9YIuSdh6X976V.jpg", releaseDate: "2023-07-12", duration: 163, genres: "Action, Adventure, Thriller", videoUrl: "https://www.youtube.com/watch?v=avz06PDqDbM" },
    { title: "The Batman", rating: 7.8, totalrating: 720000, description: "Batman investigates the city's hidden corruption.", image: "https://image.tmdb.org/t/p/w500/74xTEgt7R36FpZ6p69786vS8n63.jpg", releaseDate: "2022-03-04", duration: 176, genres: "Action, Crime, Drama", videoUrl: "https://www.youtube.com/watch?v=mqqft22S8R8" },
    { title: "Oppenheimer", rating: 8.4, totalrating: 420000, description: "The story of American scientist J. Robert Oppenheimer.", image: "https://image.tmdb.org/t/p/w500/8Gxv3mYgiFAHUqvXo89vMvUNpY4.jpg", releaseDate: "2023-07-21", duration: 180, genres: "Biography, Drama, History", videoUrl: "https://www.youtube.com/watch?v=uYPbbksJxIg" },
    { title: "Barbie", rating: 6.9, totalrating: 380000, description: "Barbie suffers a crisis that leads her to question her world.", image: "https://image.tmdb.org/t/p/w500/iuFNmBTD0Atv4vT0C9QwoS6p3QT.jpg", releaseDate: "2023-07-21", duration: 114, genres: "Adventure, Comedy, Fantasy", videoUrl: "https://www.youtube.com/watch?v=pBk4NYhWNMM" },
    { title: "Dune", rating: 8.0, totalrating: 680000, description: "A noble family becomes embroiled in a war for control over the galaxy.", image: "https://image.tmdb.org/t/p/w500/d5N0unRiSFEfp6pSGsYArasNc4S.jpg", releaseDate: "2021-10-22", duration: 155, genres: "Action, Adventure, Sci-Fi", videoUrl: "https://www.youtube.com/watch?v=n9xhJrPXop4" },
    { title: "Top Gun: Maverick", rating: 8.3, totalrating: 650000, description: "Pete Mitchell is where he belongs as one of the Navy's top aviators.", image: "https://image.tmdb.org/t/p/w500/62HCnUTziyMC96wYvUaPZpViZld.jpg", releaseDate: "2022-05-27", duration: 130, genres: "Action, Drama", videoUrl: "https://www.youtube.com/watch?v=giXcoGa8nzo" },
    { title: "Everything Everywhere All at Once", rating: 7.8, totalrating: 480000, description: "A middle-aged Chinese immigrant is swept up in an insane adventure.", image: "https://image.tmdb.org/t/p/w500/r9p9p7v5Mhp9HpjR9p9p7v5Mhp9.jpg", releaseDate: "2022-03-25", duration: 139, genres: "Action, Adventure, Comedy", videoUrl: "https://www.youtube.com/watch?v=wxN1T1uxQ2g" },
    { title: "Squid Game", rating: 8.2, totalrating: 1500000, description: "Hundreds of cash-strapped players accept a strange invitation to compete.", image: "https://image.tmdb.org/t/p/w500/vV9Sux8TMvIB90jthtx9779S9Px7.jpg", releaseDate: "2021-09-17", duration: 54, genres: "Drama, Thriller, Survival", videoUrl: "https://www.youtube.com/watch?v=oqxAJKy0ii4" },
    { title: "Mai", rating: 8.0, totalrating: 500000, description: "Một người phụ nữ mạnh mẽ vượt qua nghịch cảnh.", image: "https://image.tmdb.org/t/p/w500/6vS7I76XZST7Oasq7tL6pA8398r.jpg", releaseDate: "2024-02-10", duration: 120, genres: "Drama, Romance", videoUrl: "https://www.youtube.com/watch?v=Yz96EBNwMGw" },
    { title: "Deadpool & Wolverine", rating: 8.0, totalrating: 130000, description: "Deadpool and Wolverine team up to defeat a common enemy.", image: "https://image.tmdb.org/t/p/w500/j69vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2024-07-26", duration: 128, genres: "Action, Adventure, Comedy", videoUrl: "https://www.youtube.com/watch?v=73_1biulkYk" },
    { title: "Inside Out 2", rating: 7.9, totalrating: 120000, description: "Riley's mind headquarters is undergoing a sudden demolition.", image: "https://image.tmdb.org/t/p/w500/vpnVMZ9R69vWo7vY99A997BInpM.jpg", releaseDate: "2024-06-14", duration: 96, genres: "Animation, Family, Drama", videoUrl: "https://www.youtube.com/watch?v=LEjhY15eCx0" },
    { title: "Despicable Me 4", rating: 7.3, totalrating: 29000, description: "Gru faces a new nemesis in Maxime Le Mal.", image: "https://image.tmdb.org/t/p/w500/wWbaUB69vWo7vY99A997BInpM5a.jpg", releaseDate: "2024-07-03", duration: 95, genres: "Animation, Action, Family", videoUrl: "https://www.youtube.com/watch?v=qQlr9-rF32A" },
    { title: "A Quiet Place: Day One", rating: 7.0, totalrating: 34000, description: "New York City is invaded by alien creatures that hunt by sound.", image: "https://image.tmdb.org/t/p/w500/yrp9vWo7vY99A997BInpM5aKu98.jpg", releaseDate: "2024-06-28", duration: 100, genres: "Horror, Sci-Fi, Thriller", videoUrl: "https://www.youtube.com/watch?v=YPY7J-flzE8" },
    { title: "The Substance", rating: 7.9, totalrating: 15000, description: "A product allows you to generate another you: younger, more beautiful.", image: "https://image.tmdb.org/t/p/w500/l9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2024-09-20", duration: 140, genres: "Horror, Drama, Comedy", videoUrl: "https://www.youtube.com/watch?v=LNlrGhBpYjc" },
    { title: "The Fall Guy", rating: 7.3, totalrating: 112000, description: "A down-and-out stuntman must find a missing star.", image: "https://image.tmdb.org/t/p/w500/p9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2024-05-03", duration: 126, genres: "Action, Comedy", videoUrl: "https://www.youtube.com/watch?v=j7jPnwVGdZ8" },
    { title: "Twisters", rating: 7.0, totalrating: 18000, description: "Kate Cooper is lured back to the open plains to test a tracking system.", image: "https://image.tmdb.org/t/p/w500/8vWo7vY99A997BInpM5aKu986S6.jpg", releaseDate: "2024-07-19", duration: 122, genres: "Action, Adventure, Thriller", videoUrl: "https://www.youtube.com/watch?v=U24D6sXdNxg" },
    { title: "Fly Me to the Moon", rating: 6.7, totalrating: 11000, description: "Marketing maven Kelly Jones wreaks havoc on launch director Cole Davis's task.", image: "https://image.tmdb.org/t/p/w500/r9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2024-07-12", duration: 132, genres: "Comedy, Romance", videoUrl: "https://www.youtube.com/watch?v=lW7enw6mFxs" },
    { title: "Kinds of Kindness", rating: 7.2, totalrating: 13000, description: "A man without choice tries to take control of his own life.", image: "https://image.tmdb.org/t/p/w500/k9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2024-06-21", duration: 165, genres: "Drama, Comedy", videoUrl: "https://www.youtube.com/watch?v=NGOL2_mI9Hw" },
    { title: "The Garfield Movie", rating: 7.1, totalrating: 38000, description: "Garfield has a wild outdoor adventure with his father Vic.", image: "https://image.tmdb.org/t/p/w500/f9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2024-05-24", duration: 101, genres: "Animation, Comedy, Family", videoUrl: "https://www.youtube.com/watch?v=IeFWNtMo1Fs" },
    { title: "IF", rating: 7.4, totalrating: 41000, description: "A young girl begins to see everyone's imaginary friends.", image: "https://image.tmdb.org/t/p/w500/i9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2024-05-17", duration: 104, genres: "Comedy, Family, Fantasy", videoUrl: "https://www.youtube.com/watch?v=mb2187ZQtBE" },
    { title: "The Iron Claw", rating: 7.7, totalrating: 45000, description: "The true story of the inseparable Von Erich brothers.", image: "https://image.tmdb.org/t/p/w500/t9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-12-22", duration: 132, genres: "Drama, Sport", videoUrl: "https://www.youtube.com/watch?v=8KVsaoveTbw" },
    { title: "Anatomy of a Fall", rating: 7.8, totalrating: 110000, description: "A woman is suspected of her husband's murder.", image: "https://image.tmdb.org/t/p/w500/a9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-08-23", duration: 152, genres: "Thriller, Mystery, Drama", videoUrl: "https://www.youtube.com/watch?v=fTrsp5BMloA" },
    { title: "Saltburn", rating: 7.2, totalrating: 234000, description: "A student at Oxford finds himself drawn into the world of a classmate.", image: "https://image.tmdb.org/t/p/w500/s9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-11-17", duration: 131, genres: "Drama, Comedy, Thriller", videoUrl: "https://www.youtube.com/watch?v=lALMdJf6UUE" },
    { title: "The Holdovers", rating: 7.9, totalrating: 130000, description: "A cranky history teacher is forced to remain on campus with a student.", image: "https://image.tmdb.org/t/p/w500/h9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-10-27", duration: 133, genres: "Comedy, Drama", videoUrl: "https://www.youtube.com/watch?v=AhKLpJmHhIg" },
    { title: "Priscilla", rating: 7.0, totalrating: 53000, description: "Teenage Priscilla Beaulieu meets Elvis Presley.", image: "https://image.tmdb.org/t/p/w500/p9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-10-27", duration: 113, genres: "Drama, Romance", videoUrl: "https://www.youtube.com/watch?v=DBWk6BohVXk" },
    { title: "Eileen", rating: 6.8, totalrating: 23000, description: "The friendship between two women at a youth prison takes a dark turn.", image: "https://image.tmdb.org/t/p/w500/e9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-12-01", duration: 97, genres: "Drama, Thriller, Mystery", videoUrl: "https://www.youtube.com/watch?v=arLbYhyP_14" },
    { title: "Killers of the Flower Moon", rating: 7.6, totalrating: 180000, description: "Members of the Osage tribe are murdered under mysterious circumstances.", image: "https://image.tmdb.org/t/p/w500/k9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-10-20", duration: 206, genres: "Crime, Drama, History", videoUrl: "https://www.youtube.com/watch?v=EP34Yoxs3FQ" },
    { title: "Wonka", rating: 7.0, totalrating: 150000, description: "The story of how a young Willy Wonka became the world's greatest inventor.", image: "https://image.tmdb.org/t/p/w500/w9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-12-15", duration: 116, genres: "Adventure, Comedy, Family", videoUrl: "https://www.youtube.com/watch?v=otNh9bTjXWg" },
    { title: "Napoleon", rating: 6.4, totalrating: 120000, description: "An epic look at the French emperor Napoleon Bonaparte's rise to power.", image: "https://image.tmdb.org/t/p/w500/n9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-11-22", duration: 158, genres: "Action, Biography, Drama", videoUrl: "https://www.youtube.com/watch?v=OAZWXUkrjWG" },
    { title: "The Killer", rating: 6.7, totalrating: 90000, description: "An assassin battles his employers on an international manhunt.", image: "https://image.tmdb.org/t/p/w500/k9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-10-27", duration: 118, genres: "Action, Crime, Drama", videoUrl: "https://www.youtube.com/watch?v=5S7FR_HCg9g" },
    { title: "Leave the World Behind", rating: 6.5, totalrating: 85000, description: "A family's getaway takes an ominous turn when two strangers arrive.", image: "https://image.tmdb.org/t/p/w500/l9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-12-08", duration: 138, genres: "Drama, Sci-Fi, Thriller", videoUrl: "https://www.youtube.com/watch?v=cMVBC_9S0O4" },
    { title: "Society of the Snow", rating: 7.8, totalrating: 75000, description: "A flight carrying a rugby team crashes in the Andes.", image: "https://image.tmdb.org/t/p/w500/s9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-12-13", duration: 144, genres: "Adventure, Biography, Drama", videoUrl: "https://www.youtube.com/watch?v=pDak4qLyFzY" },
    { title: "Ferrari", rating: 6.5, totalrating: 45000, description: "Ex-racer Enzo Ferrari is in crisis.", image: "https://image.tmdb.org/t/p/w500/f9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-12-25", duration: 130, genres: "Biography, Drama, History", videoUrl: "https://www.youtube.com/watch?v=KZHX6S6-Kog" },
    { title: "The Zone of Interest", rating: 7.5, totalrating: 55000, description: "The commandant of Auschwitz strives to build a dream life.", image: "https://image.tmdb.org/t/p/w500/z9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-12-15", duration: 105, genres: "Drama, History, War", videoUrl: "https://www.youtube.com/watch?v=fXvI_7I_Nms" },
    { title: "The Creator", rating: 6.8, totalrating: 140000, description: "A future war between the human race and artificial intelligence.", image: "https://image.tmdb.org/t/p/w500/c9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-09-29", duration: 133, genres: "Action, Adventure, Sci-Fi", videoUrl: "https://www.youtube.com/watch?v=ex3C1pB_C_M" },
    { title: "No One Will Save You", rating: 6.3, totalrating: 65000, description: "An exiled homebody battles an alien in her home.", image: "https://image.tmdb.org/t/p/w500/n9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-09-22", duration: 93, genres: "Horror, Sci-Fi, Thriller", videoUrl: "https://www.youtube.com/watch?v=27mD69v_2Yk" },
    { title: "Talk to Me", rating: 7.1, totalrating: 110000, description: "Friends discover how to conjure spirits using an embalmed hand.", image: "https://image.tmdb.org/t/p/w500/t9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-07-28", duration: 95, genres: "Horror, Thriller", videoUrl: "https://www.youtube.com/watch?v=aLAKJu9aUXA" },
    { title: "Blue Beetle", rating: 6.0, totalrating: 95000, description: "An alien scarab chooses Jaime Reyes to be its host.", image: "https://image.tmdb.org/t/p/w500/b9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-08-18", duration: 127, genres: "Action, Adventure, Sci-Fi", videoUrl: "https://www.youtube.com/watch?v=vS3_72Gb-bI" },
    { title: "Gran Turismo", rating: 7.2, totalrating: 85000, description: "A teenage Gran Turismo player becomes a professional racecar driver.", image: "https://image.tmdb.org/t/p/w500/g9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-08-25", duration: 134, genres: "Action, Adventure, Drama", videoUrl: "https://www.youtube.com/watch?v=GVPzGBvPrzw" },
    { title: "Meg 2: The Trench", rating: 5.0, totalrating: 75000, description: "A research team explores the deepest depths of the ocean.", image: "https://image.tmdb.org/t/p/w500/m9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-08-04", duration: 116, genres: "Action, Adventure, Sci-Fi", videoUrl: "https://www.youtube.com/watch?v=dG91B3hHyY4" },
    { title: "A Haunting in Venice", rating: 6.5, totalrating: 65000, description: "Poirot attends a seance at a decaying, haunted palazzo.", image: "https://image.tmdb.org/t/p/w500/a9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-09-15", duration: 103, genres: "Crime, Drama, Horror", videoUrl: "https://www.youtube.com/watch?v=yedaVvB_Ckw" },
    { title: "The Equalizer 3", rating: 6.8, totalrating: 85000, description: "Robert McCall battles the local crime bosses in Southern Italy.", image: "https://image.tmdb.org/t/p/w500/e9vWo7vY99A997BInpM5aKu986S.jpg", releaseDate: "2023-09-01", duration: 109, genres: "Action, Crime, Thriller", videoUrl: "https://www.youtube.com/watch?v=19iSXY222S8" }
];

const finalReseed = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('Connected to MongoDB for definitive reseed (OPEN PROXY)...');

        const finalMovies = finalMoviesData.map(m => ({
            ...m,
            image: getOpenSourceImageUrl(m.image)
        }));

        await Movie.deleteMany({});
        console.log('Old movies deleted.');

        await Movie.insertMany(finalMovies);
        console.log(`${finalMovies.length} movies with OPEN-SOURCE PROXY images imported successfully!`);

        process.exit();
    } catch (error) {
        console.error('Error in definitive reseed:', error);
        process.exit(1);
    }
};

finalReseed();
